name: Stage DB Deployment (VM)

on:
  push:
    branches:
      - main

jobs:
  deploy-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ✅ Debug GCP authentication
      - name: Debug GCP Project
        run: |
          gcloud auth list
          gcloud config list project

      # ✅ Copy changelogs to VM using gcloud compute scp
      - name: Copy changelogs to VM
        run: |
          echo "Copying changelogs to VM..."
          gcloud compute scp --recurse db github-ssh-sa@${{ secrets.VM_NAME }}:/home/github-ssh-sa/liquibase-project --zone=${{ secrets.VM_ZONE }}

      # ✅ Check files on VM
      - name: Check files on VM
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: ${{ secrets.VM_NAME }}
          zone: ${{ secrets.VM_ZONE }}
          user: github-ssh-sa
          command: |
            echo "Listing files on VM"
            ls -l /home/github-ssh-sa/liquibase-project

      # ✅ Run Liquibase on VM
      - name: Run Liquibase on VM
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: ${{ secrets.VM_NAME }}
          zone: ${{ secrets.VM_ZONE }}
          user: github-ssh-sa
          command: |
            cd /home/github-ssh-sa/liquibase-project
            echo "Running Liquibase update..."
            liquibase \
              --url="${{ secrets.DB_URL }}" \
              --username=${{ secrets.DB_USER }} \
              --password=${{ secrets.DB_PASS }} \
              --changelog-file=db/changelog-master.xml \
              tag "build-${GITHUB_RUN_NUMBER}"
            liquibase \
              --url="${{ secrets.DB_URL }}" \
              --username=${{ secrets.DB_USER }} \
              --password=${{ secrets.DB_PASS }} \
              --changelog-file=db/changelog-master.xml \
              update

